-- PROJECT TABLES

CREATE TABLE IF NOT EXISTS contact (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(50) NOT NULL,
  address VARCHAR(256) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS phone (
  id INT NOT NULL AUTO_INCREMENT,
  contact_id INT NOT NULL,
  phone_number VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY(contact_id) REFERENCES contact(id)
);
